//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Projects
    {
        public string ProjectID { get; set; }
        [Display(Name = "Project name: ")]
        public string ProjectName { get; set; }
        [Display(Name = "Project description: ")]
        public string ProjectDescription { get; set; }
        [Display(Name = "Project owner: ")]
        public string ProjectOwner { get; set; }
        [Display(Name = "Project members (Commas seperated): ")]
        public string ProjectMembers { get; set; }
    }
}
