//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Tasks
    {
        public string TaskID { get; set; }
        [Required]
        [DisplayName("Task name: ")]
        public string TaskName { get; set; }
        [DisplayName("Task description: ")]
        public string TaskDescription { get; set; }
        [DisplayName("Choose task status: ")]
        public string TaskStatus { get; set; }
        [Required]
        [DisplayName("Assigned user, format e.g. user@domain.com")]
        public string TaskAssignedToUser { get; set; }
    }
}
