//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tasks
    {
        public string TaskID { get; set; }
        [DisplayName("Task Name:")]
        public string TaskName { get; set; }
        [DisplayName("Task Description:")]
        public string TaskDescription { get; set; }
        [DisplayName("Task Status:")]
        public string TaskStatus { get; set; }
    }
}
